spring:
  datasource:
    password: sa
    username: 
    url: jdbc:h2:mem:aluraloja
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
